### ISSUE TITLE
unexpected inference output 'prob' for model yolov4

### ISSUE THREAD

**Issue by Abdob** [olibartfast/yolov4-triton-cpp-client#2]
the python client works with generating engine file from the example weights file downloaded in the yolov4-triton-client repo.

The python client expects input name _inputs_ and output name _detections_ whereas the c++ client expects _data_ for input and _prob_ for outputs.

**Comment by Abdob** [comment]
error message:
(base) root@wave:/yolov4-triton-tensorrt/clients/c++/build# ./yolov4-triton-cpp-client --video=/Videos/sample_720p.mp4 
Server address: localhost:8001
Video name: /Videos/sample_720p.mp4
Protocol:  grpc
Path to labels name:  ../coco.names
Created output prob
failed sending synchronous infer request: unexpected inference output 'prob' for model 'yolov4'

simply changing the names doesn't produce any detections. Has the yolov4.wts file downloaded from the google drive changed?

**Comment by olibartfast** [comment]
Yes if you are talking about weights in current yolov4-triton-tensorrt repo release. C++ client needs yolov4 wts weights (and resulting tensorrt binary)generated according to [tensorrtx](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov4) implementation, with following mapping in triton server config.pbtxt related to the deployed model
```
platform: "tensorrt_plan"
max_batch_size: 1
input {
  name: "data"
  data_type: TYPE_FP32
  dims: 3
  dims: 608
  dims: 608
}
output {
  name: "prob"
  data_type: TYPE_FP32
  dims: 7001
  dims: 1
  dims: 1
}
default_model_filename: "model.plan"
```

**Comment by Abdob** [comment]
Thanks! @olibartfast one thing was the correct yolov4.wts file and the other was the config file.
